version: '3'
services:
 # The redmine application
  redmine:
    # Build from the Dockerfile in ./app
    build: ./app
    # Will wait for the database to load before running app, to avoid errors
    depends_on:
      - db
    # Exposes port 8080  
    ports:
      - '8080:8080'
    # Set rails ennvironment to production  
    environment:
        RAILS_ENV: production  
    # Run command to run the application with unicorn
    command: unicorn

  # The postgres database  
  db:
    # Creates the database from image
    image: postgres:9.5
    # Expose postgres standard ports to allow application connection
    ports:
      - '5432:5432'
    # Set username and password  
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: redmine
    # Database volume    
    volumes:
      - post-db:/var/lib/postgresql/data
  # The reverseproxy    
  reverseproxy:
    # Build the reverseproxy from the dockerfile in reverseproxy-folder.
    build: ./reverseproxy/
    # Wait for redmine to finish running before running the reverseproxy
    depends_on:
      - redmine
    # Expose the ports being used.  
    ports:
      - 80:80
      - 443:443  
# Available volumes      
volumes:
  post-db:
